### ISSUE TITLE
addEventListener doesn't work in IE8

### ISSUE THREAD

**Issue by andrewburgess** [adambutler/diy#7]

**Comment by stuartpb** [comment]
after thorough analysis and review of every line in the entire codebase of this library, [further research](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget.addEventListener#compat-desktop) has led me to the conclusion that this appears to be an upstream bug, in Internet Explorer 8's implementation of `document.addEventListener`

## End User Steps to Fix

### Step 1

add a polyfill for `document.addEventListener`

**Comment by stuartpb** [comment]
we should probably add a note to the README / landing page with the caveat that our `$.addEventListener` function is unsupported in <IE9 with a link to this issue

or just a general note that "certain features" of `$` require polyfills for "older browsers"

we can even add a note that `$` is _auto updating_ with new feature support, what other library can promise that

**Comment by adambutler** [comment]
@stuartpb I understand... I'm already concerned that the library is getting a bit bulky. The library fortunately has a `attachEvent` method available should somebody want to implement  this functionality in IE8. I think you will find that `$` automatically exposes methods that are supported in each browser and is powered by an advanced feature that I like to call autobots.

I agree we should spread the good word that `$` takes advantage of the browser API's and automagically harnesses the power, perhaps you would submit a pull-request good sir.

**Comment by ghost** [comment]
What about dropping support for IE8? I've been putting off web development for 10 years while gaining experience in other stacks, but 2015 is here, IE8 is moribund.

**Comment by nmai** [comment]
Agreed, this library is thoroughly broken in IE8. But with IE8 currently holding 7% of market share, I think we might need to consider adding backwards compatibility even if it means making the library more bloated.

**Comment by jomo** [comment]
I disagree. [The spec clearly defines addEventListener](http://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-EventTarget-addEventListener), this is a bug in IE as @stuartpb has noted above.
The bug has already been fixed in IE, but if users do not apply updates, they're out of luck.

The same issue would remain with a fix on our side if web admins don't update their diy.js version.

**Comment by stuartpb** [comment]
For a sec I thought this was jquery/PEP#174 and I was so confused
